---
title: "Learning Git"
author: "Ada Hagan"
date: "January 9, 2019"
output: html_document
---

#General Notes to Self:
- Slow down
- Always have learners tell you the commands you should use (or what the next step might be)
- Ensure at least two examples for each concept
- Create/find at least one exercise for each concept
- Work to tie the lesson in with previously learned concepts, e.g., UNIX & R
- Spend first 5 minutes allowing learners to pull up/create github accounts & open their command line.

#Outline
- What is Git?
- How to make your filebox (setup & init)
- How to add snapshots to your filebox (add, commit)
- How to track changes between versions (diff, log)
- How to restore a previous version (checkout)
- How to choose what to track & what not to track (.gitignore)
- How to share your filebox with others (github, pull, push)
- How to collaborate with others (clone)
- How to resolve collaborative conflicts (merge, branch)

#What is Git?

**It's very important that the learners fully understand this concept!! If they don't, the rest doesn't matter.**

Imagine that you have a very large (>2k piece) puzzle that you want to put together, but you don't have a picture, so you have no idea what this puzzle is supposed to look like when it's done. So you clear off the dining room table and get to work. Because you know that this is going to take you weeks or months to finish, you decide to take polaroids to track your progress. One day, some poor unknowing soul decides to "help" you with the puzzle (maybe your cat, toddler, or drunk self...). The next morning you walk in and the puzzle is a wreck!! What do you do?

Go back to the polaroids!!

This process of taking "snapshots" of your work and storing them **_is git_**!!

The way git works is that each time you stop working, you take a snapshot, label it, and put it in your filebox for later. Because you can't keep multiple puzzles in varying stages of completion in your closet, each photo contains the _differences_ between versions, not the actual old versions. This means that git can take you from the original to version 4, back to 2, etc.

Connect the puzzle concept to git language: e.g, staging == taking a snapshot; committing == putting the snapshot in the filebox/repository

What we're going to spend the rest of our time this morning/afternoon doing, is learning how to use git: how to create a filebox, take and add snapshots, compare the differences between snapshots & choosing what you want to make snapshots of versus not. We'll also extend this puzzle analogy to talk about how you can share your project progress with others and even collaborate together. 

On a command line, Git commands are written as `git verb options`, where we tell the computer that we want to use the `git` program, and perform the `verb` action, which might be modified using `options`.

#How to make your filebox (setup & init)



**Exercise:** 

Create a filebox for the R project that you started yesterday (r-novice-inflammation?).

#How to add snapshots to your filebox (add, commit)

**Think/pair/share question:**

Which command(s) below would save the changes of `myfile.txt` to my local Git repository?

  1. `$ git commit -m "my recent changes"`

  2. `$ git init myfile.txt`
     `$ git commit -m "my recent changes"`

  3. `$ git add myfile.txt`
     `$ git commit -m "my recent changes"`

  4. `$ git commit -m myfile.txt "my recent changes"`


**Exercise:**

Create an R script called "my_functions" with a function called "get_percent" that calculates the percent of X in Y when given X and Y.

Take a snapshot and put it in your filebox along with the other files/documents in your R project folder.

#How to track changes between versions (diff, log)

**Think/pair/share**
Consider this command: `git diff [ID] mars.txt`, where [ID] is replaced with the unique identifier for your most recent commit. What do you predict this command will do if you execute it? What happens when you do execute it? Why?

**Exercise:**

Move the function `K_to_C` from its current file (?) to your new script "my_functions.R". Commit the updated files and view the changes using `git diff` and `git log`. Which do you prefer? Why?

#How to restore a previous version (checkout)

**Think/pair/share:**
Jennifer has made changes to the Python script that she has been working on for weeks, and the modifications she made this morning “broke” the script and it no longer runs. She has spent ~ 1hr trying to fix it, with no luck…

Luckily, she has been keeping track of her project’s versions using Git! Which commands below will let her recover the last committed version of her Python script called `data_cruncher.py`?

  1. `$ git checkout HEAD`

  2. `$ git checkout HEAD data_cruncher.py`

  3. `$ git checkout HEAD~1 data_cruncher.py`

  4. `$ git checkout <unique ID of last commit> data_cruncher.py`

  5. `Both 2 and 4`

**Exercise**

Restore the previous version of (?) so that your working version now has the function `K_to_C`

#How to choose what to track & what not to track (.gitignore)

**Think/pair/share:**
Given a directory structure that looks like:
```
results/data
results/plots
```
How would you ignore only results/plots and not results/data?

**Think/pair/share**

Given a directory structure that looks like:
```
results/data/position/gps/a.data
results/data/position/gps/b.data
results/data/position/gps/c.data
results/data/position/gps/info.txt
results/plots
```
What’s the shortest `.gitignore` rule you could write to ignore all `.data` files in `result/data/position/gps`? Do not ignore the `info.txt`.

#How to share your filebox with others (github, pull, push)

**Extending the puzzle analogy:** What if you're really proud of this puzzle, or you want a backup of your filebox (since it's only as safe as your house is...)? Well, you could scan those polaroids into your computer then upload them to a website (e.g., mypuzzles.com), where each puzzle has it's own webpage that contains the scanned versions of your snapshots that anybody can view! This "website" is github.

Github is a website that can house each of your fileboxes and allow other researchers to check out your code as well as acting as a cloud version of your repository. Why does this matter? 

There's a push for open science, where instead of only telling scientists what your interpretation of your data is, you also make the data avilable for them to check your work. When using programs such as R to do your calculations (insted of within excel), you can also make your code available for other researchers.

**Think/pair/share:**

In this lesson, we introduced the “git push” command. How is “git push” different from “git commit”?

**Think/pair/share:**

It happens quite often in practice that you made a typo in the remote URL. This exercise is about how to fix this kind of issue. First start by adding a remote with an invalid URL:
```
git remote add broken https://github.com/this/url/is/invalid
```
Do you get an error when adding the remote? Can you think of a command that would make it obvious that your remote URL was not valid? Can you figure out how to fix the URL (tip: use `git remote -h`)? Don’t forget to clean up and remove this remote once you are done with this exercise.

_Solution: We don’t see any error message when we add the remote (adding the remote tells git about it, but doesn’t try to use it yet). As soon as we try to use git push we’ll see an error message. The command_ `git remote set-url` _allows us to change the remote’s URL to fix it._

**Using Git from RStudio**

**Exercise:**

Set up and push your (?) repository to your github account. Explore the online track changes options.

#How to collaborate with others (clone)

**Extending the puzzle analogy again:** What if you have a best friend across the country and you're both going to work on the puzzle together. So your friend buys a copy of the same puzzle to set up in their dining room. How do you work together on it and share the progress? Through your puzzles.com!

First, your friend uses one of your snapshots (maybe the border pieces) to start putting her puzzle togther, then you work on the top left corner while they work on the bottom right corner. Then she sends snapshots and **IF** you agree, you can merge her results into your own puzzle. 

On git, this process of collaboration uses github. By making a clone of your project repository and then working on it and making their own commits, they create a "branch" of the project. When they make commits, you have the option to accept or reject their changes. If you reject, it stays separate. If you accept, then you can "MERGE" their changes with your master branch.

`git clone` copies a remote repository to create a local repository with a remote called `origin` automatically set up.

**A Basic Collaborative Workflow**
In practice, it is good to be sure that you have an updated version of the repository you are collaborating on, so you should git pull before making our changes. The basic collaborative workflow would be:

+ update your local repo with `git pull origin master`,
+ make your changes and stage them with `git add`,
+ commit your changes with `git commit -m`, and
+ upload the changes to GitHub with `git push origin master`

It is better to make many commits with smaller changes rather than of one commit with massive changes: small commits are easier to read and review

**Think/pair/share:**
The Owner pushed commits to the repository without giving any information to the Collaborator. How can the Collaborator find out what has changed with command line? And on GitHub?

**Exercise:**
Switch roles and repeat the whole process.

#How to resolve collaborative conflicts (merge, branch)

**Think/pair/share**

You sit down at your computer to work on a shared project that is tracked in a remote Git repository. During your work session, you take the following actions, but not in this order:

+ _Make changes_ by appending the number `100` to a text file `numbers.txt`
+ _Update remote_ repository to match the local repository
+ _Celebrate_ your success
+ _Update local_ repository to match the remote repository
+ _Stage changes_ to be committed
+ _Commit changes_ to the local repository

In what order should you perform these actions to minimize the chances of conflicts? Put the commands above in order in the action column of the table below. When you have the order right, see if you can write the corresponding commands in the command column. A few steps are populated to get you started.
order 	action . . . . . . . . . . 	command . . . . . . . . . .
```
1 	  	 
2 	  	                              echo 100 >> numbers.txt
3 	  	 
4 	  	 
5 	  	 
6 	    Celebrate! 	                  AFK
```

**Exercise:**

Clone the repository created by your instructor. Add a new file to it, and modify an existing file (your instructor will tell you which one). When asked by your instructor, pull her changes from the repository to create a conflict, then resolve it.